### ISSUE TITLE
"This site has been reported as unsafe" and "Deceptive site ahead"

### ISSUE THREAD

**Issue by RobJohnston** [OpenDRR/opendrr.github.io#2]
I went to this site this morning using the latest FireFox and got a big red screen with the warning, "Deceptive site ahead".  Viewing the details leads to this link:  https://transparencyreport.google.com/safe-browsing/search?url=https:%2F%2Fopendrr.github.io%2F  Google is reporting that the site is unsafe because it contains pages that, "try to trick visitors into sharing personal info or downloading software".

Oddly, Chrome works.

Tried again with Edge and got, "This site has been reported as unsafe" with the details, "Microsoft recommends you don't continue to this site. It has been reported to Microsoft for containing phishing threats which may try to steal personal or financial information".

**Comment by jvanulde** [comment]
Anthony please update this issue. I understand that we've made some headway on resolving these types of errors.

**Comment by anthonyfok** [comment]
@jvanulde Thank you for notifying me of this issue!  I totally missed this one.

@RobJohnston, thank you so much for reporting!

An equivalent issue was opened by me at https://github.com/OpenDRR/opendrr-platform/issues/119 back on March 13, and thankfully, it got resolved on the same day (within 12 hours of initial discovery) thanks to Google's responsiveness.

The "story" continues on April 14 when it was discovered that CIRA Canadian Shield DNS (which I happened to be using) was blocking our opendrr.github.io site, and VirusTotal detects up to 10 security vendors misclassifying out site as suspicious, phishing or malicious.  Please see the "story" development at https://github.com/OpenDRR/opendrr-platform/issues/122

**Comment by anthonyfok** [comment]
Since this particular problem has been dealt with in OpenDRR/opendrr-platform#119, I think I should close this issue.

CIRA DNS and the few security vendors listed at VirusTotal will be followed up to OpenDRR/opendrr-platform#122.
